- name: install tomcat server
  hosts: all
  become: true
  # become_method: su
  # become_user: vagrant
  # become_method: sudo
  # remote_user: root

  vars:
    apache_tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
    apache_tomcat_tar: apache-tomcat-9.0.56.tar.gz
    apache_tomcat_dir: apache-tomcat-9.0.56

  tasks:
  - name: install OpenJDK
    yum: 
      name: java-11-openjdk-devel.x86_64

  - name: tomcat - download
    get_url: 
      url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
      dest: /home/vagrant/program
  
  - name: tomcat - extract
    unarchive:
      src: /home/vagrant/program/apache-tomcat-9.0.56.tar.gz
      dest: /home/vagrant/program
      remote_src: yes

  - name: tomcat - create symbolic
    shell: |
      cd program
      ln -s {{ apache_tomcat_dir }} tomcat

  - name: tomcat - start
    shell: |
      sudo nohup /home/vagrant/program/tomcat/bin/startup.sh
