FROM ubuntu:20.04

RUN apt update -y
RUN apt install -y net-tools
RUN apt install -y dnsutils
RUN apt install -y iputils-ping
RUN apt install -y curl wget

RUN mkdir this_linux_was_created_by_vagrant_up

# CMD ["date"]
