- name: install tomcat server
  hosts: all
  # become: true
  # become_method: sudo
  # remote_user: root

  vars:
    apache_tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
    apache_tomcat_tar: apache-tomcat-9.0.56.tar.gz
    apache_tomcat_dir: apache-tomcat-9.0.56

  tasks:
  - name: install OpenJDK
    become: true
    yum: 
      name: java-11-openjdk-devel.x86_64

  - name: apache-tomcat - download & extract & create symbolic
    shell: |
      wget -P ~/program {{ apache_tomcat_url }} --no-check-certificate
      cd ~/program
      tar xvf {{ apache_tomcat_tar }}
      ln -s {{ apache_tomcat_dir }} tomcat

  - name: apache-tomcat - start
    shell: ~/program/tomcat/bin/startup.sh
