
Vagrant.configure("2") do |config|

  config.vm.provider "docker" do |d|
    d.image = "centos:7"
    d.cmd = ["/usr/bin/tail", "-f", "/dev/null"]
    d.remains_running = true
    d.has_ssh = true
  end

end
