
Vagrant.configure("2") do |config|

  # was1
  config.vm.define "was1" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "was1"
    end
    cfg.vm.host_name = "was1"
    cfg.vm.network "public_network", ip: "192.168.1.11"
    cfg.vm.network "forwarded_port", guest: 22, host: 50022, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: 50080, auto_correct: true
    cfg.vm.network "forwarded_port", guest: 8080, host: 58080, auto_correct: true
    cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true
    cfg.vm.provision "shell", inline: "sudo yum update -y"
    cfg.vm.provision "shell", inline: "sudo yum install -y net-tools"
    cfg.vm.provision "shell", inline: "sudo yum install -y bind-utils"
  end

end
