
Vagrant.configure("2") do |config|

  # common
  config.vm.box = "ubuntu/focal64"
  # config.vm.box = "hashicorp/bionic64"

  # ubuntu1
  config.vm.define "ubuntu1" do |cfg|
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu1"
    end
    cfg.vm.host_name = "ubuntu1"
    cfg.vm.network "public_network", ip: "192.168.1.11"
    cfg.vm.network "forwarded_port", guest: 22, host: 51121, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: 51180, auto_correct: true
    cfg.vm.network "forwarded_port", guest: 8080, host: 51188, auto_correct: true
  end

  # ansible-server
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-server"
    end
    cfg.vm.host_name = "ansible-server"
    cfg.vm.network "public_network", ip: "192.168.1.12"
    cfg.vm.network "forwarded_port", guest: 22, host: 51222, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder ".", "/home/vagrant/shared_data"
    # install ansible
    cfg.vm.provision "shell", inline: <<-SCRIPT
      sudo apt update -y
      # sudo apt install apt-transport-https
      # sudo apt install software-properties-common
      sudo apt-add-repository ppa:ansible/ansible
      sudo apt update -y
      sudo apt install -y ansible
    SCRIPT
  end

end
