# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    #ansible-client01
    config.vm.define "ansible-client01" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "ansible-client01"
      end
      cfg.vm.host_name = "ansible-client01"
      cfg.vm.network "public_network", ip: "192.168.1.1"
      cfg.vm.network "forwarded_port", guest: 22, host: 60001, auto_correct: true, id: "ssh"
      cfg.vm.network "forwarded_port", guest: 80, host: 60081, auto_correct: true
      cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true
    end

    #ansible-client02
    config.vm.define "ansible-client02" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "ansible-client02"
      end
      cfg.vm.host_name = "ansible-client02"
      cfg.vm.network "public_network", ip: "192.168.1.2"
      cfg.vm.network "forwarded_port", guest: 22, host: 60002, auto_correct: true, id: "ssh"
      cfg.vm.network "forwarded_port", guest: 80, host: 60082, auto_correct: true
      cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true
    end

    #ansible-client03
    config.vm.define "ansible-client03" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "ansible-client03"
      end
      cfg.vm.host_name = "ansible-client03"
      cfg.vm.network "public_network", ip: "192.168.1.3"
      cfg.vm.network "forwarded_port", guest: 3306, host: 13306, auto_correct: true
      cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true
    end

    #ansible-server
    config.vm.define "ansible-server" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "ansible-server"
      end
      cfg.vm.host_name = "ansible-server"
      cfg.vm.network "public_network", ip: "192.168.1.11"
      cfg.vm.network "forwarded_port", guest: 22, host: 60011, auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../shared_data", "/shared_data", disabled: true
      cfg.vm.provision "shell", inline: "yum install epel-release -y"
      cfg.vm.provision "shell", inline: "yum install ansible -y"
      cfg.vm.provision "shell", inline: "yum install tree -y"
    end

end
